
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: easyshop-sql
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
